name: Loader
version: '1.2.1'
main: io.reallmerry.rstudio.loader.Loader
authors: [ reallmerry ]
description: Автоматический загрузчик для тестовых серверов
website: https://reallmerry.store
folia-supported: true